function [paper_tbl, channel_tbl, synapse_tbl] = swr_build_paper_tables()
% Build paper-level summary tables for channel kinetics and synapse models.
%
% Scope:
%   - Core SWR papers + BlueBrain/Bezaire CA1 references used in this repo.
%   - Channel table is one row per channel mechanism (no grouped channels).
%   - PC and PVBC are expanded in detail for Canakci, BlueBrain, and Bezaire.
%
% Output tables:
%   paper_tbl   : one row per paper
%   channel_tbl : one row per channel/mechanism
%   synapse_tbl : one row per directed synaptic connection template

paper_rows = {
    'Evangelista2020', 'Evangelista et al. 2020', 'conductance-based LIF', false, ...
        'No explicit HH ion-channel gates; membrane and synaptic time constants are reported.';
    'Jahnke2015', 'Jahnke et al. 2015', 'LIF + alpha kernel', false, ...
        'No explicit HH ion-channel gates; alpha-kernel synapses and gsyn decay are reported.';
    'Taxidis2012', 'Taxidis et al. 2012', 'CA3-CA1 two-area biophysical network', true, ...
        'Uses Pinsky-Rinzel pyramidal and reduced Traub/Miles interneuron templates.';
    'RamirezVillegas2018', 'Ramirez-Villegas et al. 2018', 'multi-compartment CA3-CA1 biophysical network', true, ...
        'Uses Pinsky-Rinzel pyramidal and reduced Traub/Miles interneuron templates; full constants in supplemental tables.';
    'Canakci2017', 'Canakci et al. 2017', 'NEURON biophysical network', true, ...
        'Channel-rate equations available from associated ModelDB mechanisms (ca1ina, ca1ikdr, nafbwb, kdrbwb).';
    'BlueBrainCA1', 'Blue Brain CA1 cellular mechanisms (as used in this repository SONATA dynamics)', ...
        'single-cell conductance mechanisms embedded in CA1 network context', true, ...
        'PC/PVBC soma channels pulled from SONATA dynamics JSON and NEURON mod kinetics.';
    'Bezaire2017', 'Bezaire et al. full-scale CA1 model (repository: mbezaire/ca1)', ...
        'full-scale CA1 network model with multicompartment biophysics and event-based synapses', true, ...
        'This table focuses on PC and PVBC channels/synapses and mechanism equations from the CA1 mod files.'
};

paper_tbl = cell2table(paper_rows, 'VariableNames', ...
    {'paper_id','citation','model_type','has_explicit_ion_kinetics','notes'});

channel_rows = {
    % Evangelista 2020 (LIF)
    'Evangelista2020','Evangelista et al. 2020','PC/PVBC/anti-SWR LIF','N/A (LIF membrane model)', ...
    'tau_m*dV/dt = -(V-E_L) + R*I_syn', 'N/A', 'N/A', ...
    'No channel opening/closing gates in manuscript LIF formulation.', ...
    'PMCID: PMC7548694';

    % Jahnke 2015 (LIF)
    'Jahnke2015','Jahnke et al. 2015','E/I LIF populations','N/A (LIF membrane model)', ...
    'tau_m*dV/dt = (E_L-V) + R_m*(I_bg + I_syn + I_signal)', 'N/A', 'N/A', ...
    'No channel opening/closing gates; single-compartment LIF with conductance-based synapses.', ...
    'J Neurosci 2015, DOI 10.1523/JNEUROSCI.3977-14.2015';

    % Taxidis 2012 (template-based biophysical cells)
    'Taxidis2012','Taxidis et al. 2012','CA3/CA1 pyramidal (2-comp)','I_Na (somatic, template)', ...
    'Template conductance model from Pinsky-Rinzel; gate dynamics in cited source.', ...
    '1-x_inf(V) template-defined', ...
    'dx/dt = (x_inf(V)-x)/tau_x(V), template-defined', ...
    'Tau constants not restated in SWR paper; see Pinsky-Rinzel 1994 parameterization.', ...
    'Hippocampus 2012, DOI 10.1002/hipo.20930';
    'Taxidis2012','Taxidis et al. 2012','CA3/CA1 pyramidal (2-comp)','I_KDR (somatic, template)', ...
    'Template conductance model from Pinsky-Rinzel; gate dynamics in cited source.', ...
    '1-x_inf(V) template-defined', ...
    'dx/dt = (x_inf(V)-x)/tau_x(V), template-defined', ...
    'Tau constants not restated in SWR paper; see Pinsky-Rinzel 1994 parameterization.', ...
    'Hippocampus 2012, DOI 10.1002/hipo.20930';
    'Taxidis2012','Taxidis et al. 2012','CA3/CA1 pyramidal (2-comp)','I_Ca / I_KCa / I_KAHP (dendritic, template)', ...
    'Template conductance model from Pinsky-Rinzel; Ca-dependent gates in cited source.', ...
    '1-x_inf(V,[Ca]) template-defined', ...
    'dx/dt = (x_inf-x)/tau_x and/or Ca-dependent kinetics, template-defined', ...
    'Tau constants not restated in SWR paper; see Pinsky-Rinzel 1994 parameterization.', ...
    'Hippocampus 2012, DOI 10.1002/hipo.20930';
    'Taxidis2012','Taxidis et al. 2012','CA3/CA1 interneuron (reduced)','I_Na / I_KDR (template)', ...
    'Reduced Traub/Miles-type conductance model as stated by manuscript.', ...
    '1-x_inf(V) template-defined', ...
    'dx/dt = (x_inf(V)-x)/tau_x(V), template-defined', ...
    'Tau constants not restated in SWR paper; see cited template models.', ...
    'Hippocampus 2012, DOI 10.1002/hipo.20930';

    % Ramirez-Villegas 2018 (template-based biophysical cells)
    'RamirezVillegas2018','Ramirez-Villegas et al. 2018','CA3/CA1 pyramidal (2-comp)','I_Na / I_KDR / I_Ca / I_KCa / I_KAHP (template)', ...
    'Method details state Pinsky-Rinzel 2-comp pyramidal model with original parameters.', ...
    '1-x_inf(V,[Ca]) template-defined', ...
    'dx/dt = (x_inf-x)/tau_x and Ca-dependent kinetics from template', ...
    'Values provided in supplemental parameter tables (S1/S4), not fully restated in main text.', ...
    'Neuron 2018, DOI 10.1016/j.neuron.2018.09.041';
    'RamirezVillegas2018','Ramirez-Villegas et al. 2018','CA3/CA1 interneuron (2-comp reduced)','I_Na / I_K (template)', ...
    'Method details state reduced Traub and Miles-based interneuron with minimal active currents.', ...
    '1-x_inf(V) template-defined', ...
    'dx/dt = (x_inf(V)-x)/tau_x(V), template-defined', ...
    'Values provided in supplemental parameter tables, not fully restated in main text.', ...
    'Neuron 2018, DOI 10.1016/j.neuron.2018.09.041';

    % Canakci 2017 (explicit equations from model mechanisms; one row per channel)
    'Canakci2017','Canakci et al. 2017','CA1 pyramidal','Na (m,h,i) from ca1ina.mod', ...
    ['m_inf=a_m/(a_m+b_m), h_inf=1/(1+exp((V+50)/4)), ' ...
     'i_inf=(1+ki*exp((V-vi)/2))/(1+exp((V-vi)/2))'], ...
    '1-m_inf; 1-h_inf; 1-i_inf', ...
    ['tau_m=max(0.5/(a_m+b_m),0.02), tau_h=max(0.5/(a_h+b_h),0.5), ' ...
     'tau_i=max(3000*b_i/(1+a_i),10)'], ...
    'vi=-60 mV, ki=0.8; m_min=0.02 ms, h_min=0.5 ms, i_min=10 ms', ...
    'ModelDB 230861 (ca1ina.mod)';
    'Canakci2017','Canakci et al. 2017','CA1 pyramidal','KDR (n) from ca1ikdr.mod', ...
    'n_inf=1/(1+exp(-0.11*(V-13)))', ...
    '1-n_inf', ...
    'tau_n=max(50*exp(-0.08*(V-13))/(1+exp(-0.11*(V-13))),2)', ...
    'n_min=2 ms', ...
    'ModelDB 230861 (ca1ikdr.mod)';
    'Canakci2017','Canakci et al. 2017','PV basket','Na fast (m_inf instantaneous, h state) from nafbwb.mod', ...
    ['m_inf=a_m/(a_m+b_m) with a_m=fun3(V,-35,-0.1,-10), b_m=fun1(V,-60,4,-18); ' ...
     'h_inf=a_h/(a_h+b_h)'], ...
    '1-m_inf; 1-h_inf', ...
    'tau_h=1/((a_h+b_h)*q10_h), q10_h=5^((T-27)/10); m treated instantaneous', ...
    'T=34 C default, q10 reference 27 C', ...
    'ModelDB 230861 (nafbwb.mod)';
    'Canakci2017','Canakci et al. 2017','PV basket','KDR (n) from kdrbwb.mod', ...
    'n_inf=a_n/(a_n+b_n) with a_n=fun3(V,-34,-0.01,-10), b_n=fun1(V,-44,0.125,-80)', ...
    '1-n_inf', ...
    'tau_n=1/((a_n+b_n)*q10_n), q10_n=5^((T-27)/10)', ...
    'T=34 C default, q10 reference 27 C', ...
    'ModelDB 230861 (kdrbwb.mod)';

    % BlueBrain CA1 PC/PVBC (this repo SONATA + mod equations)
    'BlueBrainCA1','Blue Brain CA1 (this repo)','PC','nax (Na fast)', ...
    'm_inf=a_m/(a_m+b_m); h_inf=1/(1+exp((V-thinf-sh)/qinf)); P_open=m^3*h', ...
    '1-m_inf; 1-h_inf', ...
    'tau_m=max(1/(a_m+b_m)/qt,mmin); tau_h=max(1/(a_h+b_h)/qt,hmin)', ...
    'tha=-30, qa=7.2, thi1=thi2=-45, thinf=-50, qinf=4, q10=2, mmin=0.02 ms, hmin=0.5 ms', ...
    'modfiles/naxn.mod + PC_dynamics_params_sonata.json';
    'BlueBrainCA1','Blue Brain CA1 (this repo)','PC','kdr (delayed rectifier K)', ...
    'n_inf=1/(1+alpn), alpn=exp(1e-3*zetan*(V-vhalfn)*F/(R*T)); P_open=n', ...
    '1-n_inf', ...
    'tau_n=max(betn/(qt*a0n*(1+alpn)),nmin)', ...
    'vhalfn=13, zetan=-3, gmn=0.7, a0n=0.02, q10=1, nmin=2 ms', ...
    'modfiles/kdrca1.mod + PC_dynamics_params_sonata.json';
    'BlueBrainCA1','Blue Brain CA1 (this repo)','PC','kap (A-type K proximal)', ...
    'n_inf=1/(1+alpn), l_inf=1/(1+alpl), P_open=n*l', ...
    '1-n_inf; 1-l_inf', ...
    'tau_n=betn/(qt*a0n*(1+alpn)); tau_l=max(0.26*(V+50)/qtl,lmin/qtl)', ...
    'vhalfn=11, vhalfl=-56, a0n=0.05, a0l=0.05, zetan=-1.5, zetal=3, q10=5', ...
    'modfiles/kaprox.mod + PC_dynamics_params_sonata.json';
    'BlueBrainCA1','Blue Brain CA1 (this repo)','PC','kmb (M-type K)', ...
    'm_inf=1/(1+exp((V-vhalfl-sh)/kl)); P_open=m', ...
    '1-m_inf', ...
    'tau_m=b0 + b/(a0t*(1+a))', ...
    'vhalfl=-40, kl=-10, vhalft=-42, a0t=0.003, zetat=7, gmt=0.4, b0=60', ...
    'modfiles/kmb.mod + PC_dynamics_params_sonata.json';
    'BlueBrainCA1','Blue Brain CA1 (this repo)','PC','cal (L-type Ca)', ...
    'm_inf=a/(a+b); P_open=m^2*h2, h2=cai/(cai+50uM)', ...
    '1-m_inf', ...
    'tau_m=max(betmt/(qt*a0m*(1+alpmt)),mmin/qt)', ...
    'q10=5, mmin=0.2 ms, a0m=0.1, zetam=2, vhalfm=4, gmm=0.1', ...
    'modfiles/cal2.mod + PC_dynamics_params_sonata.json';
    'BlueBrainCA1','Blue Brain CA1 (this repo)','PC','can (N-type Ca)', ...
    'm_inf=a/(a+b); h_inf=a_h/(a_h+b_h); P_open=m^2*h*h2, h2=cai/(cai+50uM)', ...
    '1-m_inf; 1-h_inf', ...
    'tau_m=max(betmt/(qt*a0m*(1+alpmt)),mmin/qt); tau_h=max(80 ms,hmin)', ...
    'q10=5, mmin=0.2 ms, hmin=3 ms, a0m=0.03, zetam=2, vhalfm=-14, gmm=0.1', ...
    'modfiles/can2.mod + PC_dynamics_params_sonata.json';
    'BlueBrainCA1','Blue Brain CA1 (this repo)','PC','cat (T-type Ca)', ...
    'm_inf=a/(a+b); h_inf=a_h/(a_h+b_h); P_open=m^2*h', ...
    '1-m_inf; 1-h_inf', ...
    'tau_m=max(betmt/(qt*a0m*(1+alpmt)),mmin); tau_h=max(beth/(a0h*(1+alph)),hmin)', ...
    'q10=5, mmin=0.2 ms, hmin=10 ms, a0m=0.04, zetam=2, vhalfm=-28, gmm=0.1', ...
    'modfiles/cat.mod + PC_dynamics_params_sonata.json';
    'BlueBrainCA1','Blue Brain CA1 (this repo)','PC','kca (Ca-dependent K)', ...
    'm_inf=(cai/cac)^4 / (1+(cai/cac)^4); P_open=m^3', ...
    '1-m_inf', ...
    'tau_m=max(1/(beta*(1+(cai/cac)^4)*tadj),taumin)', ...
    'beta=0.03, cac=3.5e-4 mM, taumin=0.5 ms, q10 base=3 (22C)', ...
    'modfiles/kca.mod + PC_dynamics_params_sonata.json';
    'BlueBrainCA1','Blue Brain CA1 (this repo)','PC','cagk (BK-like Ca-activated K)', ...
    'o_inf=a/(a+b), a=cai*abar/(cai+exp1), b=bbar/(1+cai/exp2); P_open=o', ...
    '1-o_inf', ...
    'tau_o=1/(a+b)', ...
    'd1=0.84, d2=1, k1=0.48e-3, k2=0.13e-6, abar=0.28, bbar=0.48', ...
    'modfiles/cagk.mod + PC_dynamics_params_sonata.json';

    'BlueBrainCA1','Blue Brain CA1 (this repo)','PVBC','na3 (Na fast + slow inactivation)', ...
    'm_inf=a_m/(a_m+b_m); h_inf=1/(1+exp((V-thinf-sh)/qinf)); s_inf=alpv+ar*(1-alpv); P_open=m^3*h*s', ...
    '1-m_inf; 1-h_inf; 1-s_inf', ...
    'tau_m=max(1/(a_m+b_m)/qt,mmin); tau_h=max(1/(a_h+b_h)/qt,hmin); tau_s=max(bets/(a0s*(1+alps)),smin)', ...
    'tha=-30, qa=7.2, thi1=thi2=-45, thinf=-50, qinf=4, q10=2, vhalfs=-60, a0s=0.0003, smin=10 ms', ...
    'modfiles/na3n.mod + PVBC_dynamics_params_sonata.json';
    'BlueBrainCA1','Blue Brain CA1 (this repo)','PVBC','kdrb (delayed rectifier K)', ...
    'n_inf=1/(1+alpn), alpn=exp(1e-3*zetan*(V-vhalfn-sh)*F/(R*T)); P_open=n', ...
    '1-n_inf', ...
    'tau_n=max(betn/(qt*a0n*(1+alpn)),nmin/qt)', ...
    'vhalfn=13, zetan=-3, gmn=0.7, a0n=0.02, q10=1, nmin=2 ms', ...
    'modfiles/kdrbca1.mod + PVBC_dynamics_params_sonata.json';
    'BlueBrainCA1','Blue Brain CA1 (this repo)','PVBC','kdb (D-type K)', ...
    'n_inf=1/(1+alpn), alpn=exp(1e-3*zetan*(V-vhalfn-sh)*F/(R*T)); P_open=n', ...
    '1-n_inf', ...
    'tau_n=max(betn/(qt*a0n*(1+alpn)),nmin/qt)', ...
    'vhalfn=-33, zetan=3, gmn=0.7, a0n=0.005, q10=1, nmin=2 ms', ...
    'modfiles/kdb.mod + PVBC_dynamics_params_sonata.json';
    'BlueBrainCA1','Blue Brain CA1 (this repo)','PVBC','kap (A-type K proximal)', ...
    'n_inf=1/(1+alpn), l_inf=1/(1+alpl), P_open=n*l', ...
    '1-n_inf; 1-l_inf', ...
    'tau_n=betn/(qt*a0n*(1+alpn)); tau_l=max(0.26*(V+50)/qtl,lmin/qtl)', ...
    'vhalfn=11, vhalfl=-56, a0n=0.05, a0l=0.05, zetan=-1.5, zetal=3, q10=5', ...
    'modfiles/kaprox.mod + PVBC_dynamics_params_sonata.json';
    'BlueBrainCA1','Blue Brain CA1 (this repo)','PVBC','kmb (M-type K)', ...
    'm_inf=1/(1+exp((V-vhalfl-sh)/kl)); P_open=m', ...
    '1-m_inf', ...
    'tau_m=b0 + b/(a0t*(1+a))', ...
    'vhalfl=-40, kl=-10, vhalft=-42, a0t=0.003, zetat=7, gmt=0.4, b0=60', ...
    'modfiles/kmb.mod + PVBC_dynamics_params_sonata.json';
    'BlueBrainCA1','Blue Brain CA1 (this repo)','PVBC','hd (HCN/Ih-like)', ...
    'l_inf=1/(1+exp(-(V-vhalfl)/kl)); P_open=l', ...
    '1-l_inf', ...
    'tau_l=b/(qtl*qt*a0t*(1+a))', ...
    'vhalfl=-81, kl=-8, vhalft=-75, a0t=0.011, zetat=2.2, gmt=0.4, q10=4.5', ...
    'modfiles/h.mod + PVBC_dynamics_params_sonata.json';
    'BlueBrainCA1','Blue Brain CA1 (this repo)','PVBC','cal (L-type Ca)', ...
    'm_inf=a/(a+b); P_open=m^2*h2, h2=cai/(cai+50uM)', ...
    '1-m_inf', ...
    'tau_m=max(betmt/(qt*a0m*(1+alpmt)),mmin/qt)', ...
    'q10=5, mmin=0.2 ms, a0m=0.1, zetam=2, vhalfm=4, gmm=0.1', ...
    'modfiles/cal2.mod + PVBC_dynamics_params_sonata.json';
    'BlueBrainCA1','Blue Brain CA1 (this repo)','PVBC','can (N-type Ca)', ...
    'm_inf=a/(a+b); h_inf=a_h/(a_h+b_h); P_open=m^2*h*h2, h2=cai/(cai+50uM)', ...
    '1-m_inf; 1-h_inf', ...
    'tau_m=max(betmt/(qt*a0m*(1+alpmt)),mmin/qt); tau_h=max(80 ms,hmin)', ...
    'q10=5, mmin=0.2 ms, hmin=3 ms, a0m=0.03, zetam=2, vhalfm=-14, gmm=0.1', ...
    'modfiles/can2.mod + PVBC_dynamics_params_sonata.json';
    'BlueBrainCA1','Blue Brain CA1 (this repo)','PVBC','cat (T-type Ca)', ...
    'm_inf=a/(a+b); h_inf=a_h/(a_h+b_h); P_open=m^2*h', ...
    '1-m_inf; 1-h_inf', ...
    'tau_m=max(betmt/(qt*a0m*(1+alpmt)),mmin); tau_h=max(beth/(a0h*(1+alph)),hmin)', ...
    'q10=5, mmin=0.2 ms, hmin=10 ms, a0m=0.04, zetam=2, vhalfm=-28, gmm=0.1', ...
    'modfiles/cat.mod + PVBC_dynamics_params_sonata.json';
    'BlueBrainCA1','Blue Brain CA1 (this repo)','PVBC','kca (Ca-dependent K)', ...
    'm_inf=(cai/cac)^4 / (1+(cai/cac)^4); P_open=m^3', ...
    '1-m_inf', ...
    'tau_m=max(1/(beta*(1+(cai/cac)^4)*tadj),taumin)', ...
    'beta=0.03, cac=3.5e-4 mM, taumin=0.5 ms, q10 base=3 (22C)', ...
    'modfiles/kca.mod + PVBC_dynamics_params_sonata.json';
    'BlueBrainCA1','Blue Brain CA1 (this repo)','PVBC','cagk (BK-like Ca-activated K)', ...
    'o_inf=a/(a+b), a=cai*abar/(cai+exp1), b=bbar/(1+cai/exp2); P_open=o', ...
    '1-o_inf', ...
    'tau_o=1/(a+b)', ...
    'd1=0.84, d2=1, k1=0.48e-3, k2=0.13e-6, abar=0.28, bbar=0.48', ...
    'modfiles/cagk.mod + PVBC_dynamics_params_sonata.json';

    % Bezaire full-scale CA1 (exact PC/PVBC mechanisms from mbezaire/ca1)
    'Bezaire2017','Bezaire et al. full-scale CA1 (mbezaire/ca1)','PC (poolosyncell)','ch_Navp (Na, soma/dend)', ...
    'm_inf=a_m/(a_m+b_m); h_inf=1/(1+exp((V-thinf-sh)/qinf)); s_inf=alpv+ar2*(1-alpv); P_open=m^3*h*s', ...
    '1-m_inf; 1-h_inf; 1-s_inf', ...
    'tau_m=max(1/(a_m+b_m)/qt,mmin); tau_h=max(1/(a_h+b_h)/qt,hmin); tau_s=max(bets/(a0s*(1+alps)),smax)', ...
    'sh=15, tha=-30, qa=7.2, thi1=thi2=-45, thinf=-50, qinf=4, q10=2, vhalfs=-60, a0s=3e-4, zetas=12, smax=10', ...
    'mbezaire/ca1: ch_Navp.mod + cells/class_poolosyncell.hoc';
    'Bezaire2017','Bezaire et al. full-scale CA1 (mbezaire/ca1)','PC (poolosyncell)','ch_Kdrp (KDR)', ...
    'n_inf=1/(1+alpn), alpn=exp(1e-3*zetan*(V-vhalfn)*F/(R*T)); P_open=n', ...
    '1-n_inf', ...
    'tau_n=max(betn/(qt*a0n*(1+alpn)),nmax)', ...
    'vhalfn=13, zetan=-3, gmn=0.7, a0n=0.02, q10=1, nmax=2', ...
    'mbezaire/ca1: ch_Kdrp.mod + cells/class_poolosyncell.hoc';
    'Bezaire2017','Bezaire et al. full-scale CA1 (mbezaire/ca1)','PC (poolosyncell)','ch_KvAproxp (A-type proximal)', ...
    'n_inf=1/(1+alpn), l_inf=1/(1+alpl), P_open=n*l', ...
    '1-n_inf; 1-l_inf', ...
    'tau_n=max(betn/(qt*a0n*(1+alpn)),nmin); tau_l=max(0.26*(V+50)/qtl,lmin/qtl)', ...
    'vhalfn=11, vhalfl=-56, a0n=0.05, a0l=0.05, zetan=-1.5, zetal=3, gmn=0.55, q10=5', ...
    'mbezaire/ca1: ch_KvAproxp.mod + cells/class_poolosyncell.hoc';
    'Bezaire2017','Bezaire et al. full-scale CA1 (mbezaire/ca1)','PC (poolosyncell)','ch_KvAdistp (A-type distal)', ...
    'n_inf=1/(1+alpn), l_inf=1/(1+alpl), P_open=n*l', ...
    '1-n_inf; 1-l_inf', ...
    'tau_n=max(betn/(qt*a0n*(1+alpn)),nmin); tau_l=max(0.26*(V+50)/qtl,lmin/qtl)', ...
    'vhalfn=-1, vhalfl=-56, a0n=0.1, a0l=0.05, zetan=-1.8, zetal=3, gmn=0.39, q10=5', ...
    'mbezaire/ca1: ch_KvAdistp.mod + cells/class_poolosyncell.hoc';
    'Bezaire2017','Bezaire et al. full-scale CA1 (mbezaire/ca1)','PC (poolosyncell)','ch_HCNp (Ih)', ...
    'l_inf=1/(1+exp(0.0378*zetal*(V-vhalfl))); P_open=l', ...
    '1-l_inf', ...
    'tau_l=bett/(qtl*qt*a0t*(1+alpt)), qt=q10^((T-33)/10)', ...
    'vhalfl (set in hoc: -82 or -90 by distance), vhalft=-75, a0t=0.011, zetal=4, zetat=2.2, q10=4.5', ...
    'mbezaire/ca1: ch_HCNp.mod + cells/class_poolosyncell.hoc';

    'Bezaire2017','Bezaire et al. full-scale CA1 (mbezaire/ca1)','PVBC (pvbasketcell)','ch_Navaxonp (Na)', ...
    'm_inf=a_m/(a_m+b_m); h_inf=1/(1+exp((V-thinf-sh)/qinf)); P_open=m^3*h', ...
    '1-m_inf; 1-h_inf', ...
    'tau_m=max(1/(a_m+b_m)/qt,mmin); tau_h=max(1/(a_h+b_h)/qt,hmin)', ...
    'sh=15, tha=-30, qa=7.2, thi1=thi2=-45, thinf=-50, qinf=4, q10=2, mmin=0.02, hmin=0.5', ...
    'mbezaire/ca1: ch_Navaxonp.mod + cells/class_pvbasketcell.hoc';
    'Bezaire2017','Bezaire et al. full-scale CA1 (mbezaire/ca1)','PVBC (pvbasketcell)','ch_Kdrfast (KDR fast)', ...
    'n_inf=alpha/(alpha+beta); P_open=n^4', ...
    '1-n_inf', ...
    'tau_n=1/(alpha+beta), alpha=-0.07*vtrap(V+18,-6), beta=0.264/exp((V+43)/40)', ...
    'q10=3^((T-34)/10), Yuen-Durand style', ...
    'mbezaire/ca1: ch_Kdrfast.mod + cells/class_pvbasketcell.hoc';
    'Bezaire2017','Bezaire et al. full-scale CA1 (mbezaire/ca1)','PVBC (pvbasketcell)','ch_KvA (A-type K)', ...
    'n_inf=1/(1+alpn), l_inf=1/(1+alpl), P_open=n*l', ...
    '1-n_inf; 1-l_inf', ...
    'tau_n=betn/(q10*a0n*(1+alpn)); tau_l=betl/(q10*a0l*(1+alpl))', ...
    'vhalfn=-33.6, vhalfl=-83, a0n=0.02, a0l=0.08, zetan=-3, zetal=4, gmn=0.6, q10=3^((T-30)/10)', ...
    'mbezaire/ca1: ch_KvA.mod + cells/class_pvbasketcell.hoc';
    'Bezaire2017','Bezaire et al. full-scale CA1 (mbezaire/ca1)','PVBC (pvbasketcell)','ch_CavN (N-type Ca)', ...
    'c_inf=alpha_c/(alpha_c+beta_c), d_inf=alpha_d/(alpha_d+beta_d), P_open=c^2*d', ...
    '1-c_inf; 1-d_inf', ...
    'tau_c=1/(alpha_c+beta_c); tau_d=1/(alpha_d+beta_d)', ...
    'alpha_c=-0.19*vtrap(V-19.88,-10), beta_c=0.046*exp(-V/20.73), alpha_d=1.6e-4*exp(-V/48.4)', ...
    'mbezaire/ca1: ch_CavN.mod + cells/class_pvbasketcell.hoc';
    'Bezaire2017','Bezaire et al. full-scale CA1 (mbezaire/ca1)','PVBC (pvbasketcell)','ch_CavL (L-type Ca)', ...
    'm_inf=alpha/(alpha+beta); h2(cai)=ki/(ki+cai); P_open=m^2*h2(cai)', ...
    '1-m_inf; 1-h2', ...
    'tau_m=1/(tfa*(alpha+beta))', ...
    'ki=0.001 mM, alpha=15.69*(-V+81.5)/(exp((-V+81.5)/10)-1), beta=0.29*exp(-V/10.86)', ...
    'mbezaire/ca1: ch_CavL.mod + cells/class_pvbasketcell.hoc';
    'Bezaire2017','Bezaire et al. full-scale CA1 (mbezaire/ca1)','PVBC (pvbasketcell)','ch_KCaS (Ca-activated K, small)', ...
    'q_inf=alpha/(alpha+beta), alpha=15*cai^2, beta=2.5e-4; P_open=q^2', ...
    '1-q_inf', ...
    'tau_q=1/((alpha+beta)*q10), q10=3^((T-34)/10)', ...
    'calcium-only gate (no V in alpha/beta), beta=2.5e-4', ...
    'mbezaire/ca1: ch_KCaS.mod + cells/class_pvbasketcell.hoc';
    'Bezaire2017','Bezaire et al. full-scale CA1 (mbezaire/ca1)','PVBC (pvbasketcell)','ch_KvCaB (BK-like Ca+V K)', ...
    'o_inf=alp/(alp+bet), alp=c*abar/(c+exp1), bet=bbar/(1+c/exp1); P_open=o^st', ...
    '1-o_inf', ...
    'tau_o=1/(alp+bet)', ...
    'd1=0.84, d2=1, k1=0.48e-3 mM, k2=0.13e-6 mM, abar=0.28, bbar=0.48, st=1', ...
    'mbezaire/ca1: ch_KvCaB.mod + cells/class_pvbasketcell.hoc';
    'Bezaire2017','Bezaire et al. full-scale CA1 (mbezaire/ca1)','PVBC (pvbasketcell)','iconc_Ca (intracellular Ca dynamics)', ...
    'cai'' = -(ica)/(depth*F*2)*(1e7) + (caiinf-cai)/catau', ...
    'N/A', ...
    'catau and depth define recovery and buffering timescale of cai', ...
    'depth=200 nm, catau=9 ms, caiinf=50e-6 mM, cao=2 mM', ...
    'mbezaire/ca1: iconc_Ca.mod + cells/class_pvbasketcell.hoc'
};

channel_tbl = cell2table(channel_rows, 'VariableNames', ...
    {'paper_id','citation','cell_type','channel','opening_equation','closing_equation', ...
     'tau_equation','tau_constants','source'});

synapse_rows = {
    % Evangelista 2020
    'Evangelista2020','Evangelista et al. 2020','P','P','Excitatory conductance', ...
    's(t) single-exponential conductance kernel; I_syn = g*s*(V-E_syn)', ...
    NaN, 3.0, 'Connection listed via p^{PP}; tau_s,exc=3 ms', 'PMCID: PMC7548694';
    'Evangelista2020','Evangelista et al. 2020','P','B','Excitatory conductance', ...
    's(t) single-exponential conductance kernel; I_syn = g*s*(V-E_syn)', ...
    NaN, 3.0, 'Connection listed via p^{PB}; tau_s,exc=3 ms', 'PMCID: PMC7548694';
    'Evangelista2020','Evangelista et al. 2020','A','P','Inhibitory conductance', ...
    's(t) single-exponential conductance kernel; I_syn = g*s*(V-E_syn)', ...
    NaN, 2.0, 'Connection listed via p^{AP}; tau_s,inh=2 ms', 'PMCID: PMC7548694';
    'Evangelista2020','Evangelista et al. 2020','A','A','Inhibitory conductance', ...
    's(t) single-exponential conductance kernel; I_syn = g*s*(V-E_syn)', ...
    NaN, 2.0, 'Connection listed via p^{AA}; tau_s,inh=2 ms', 'PMCID: PMC7548694';
    'Evangelista2020','Evangelista et al. 2020','A','B','Inhibitory conductance', ...
    's(t) single-exponential conductance kernel; I_syn = g*s*(V-E_syn)', ...
    NaN, 2.0, 'Connection listed via p^{AB}; tau_s,inh=2 ms', 'PMCID: PMC7548694';

    % Jahnke 2015
    'Jahnke2015','Jahnke et al. 2015','E','E','Alpha-kernel excitatory', ...
    'alpha(t)=exp(-t/tau2)-exp(-t/tau1), I_syn via conductance state g_syn', ...
    0.3, 0.6, 'Kernel taus from manuscript; separate g_syn decay tau=10 ms', ...
    'J Neurosci 2015 DOI 10.1523/JNEUROSCI.3977-14.2015';
    'Jahnke2015','Jahnke et al. 2015','E','I','Alpha-kernel excitatory', ...
    'alpha(t)=exp(-t/tau2)-exp(-t/tau1), I_syn via conductance state g_syn', ...
    0.3, 0.6, 'Kernel taus from manuscript; separate g_syn decay tau=10 ms', ...
    'J Neurosci 2015 DOI 10.1523/JNEUROSCI.3977-14.2015';
    'Jahnke2015','Jahnke et al. 2015','I','E','Alpha-kernel inhibitory', ...
    'alpha(t)=exp(-t/tau2)-exp(-t/tau1), I_syn via conductance state g_syn', ...
    0.3, 2.0, 'Kernel taus from manuscript; separate g_syn decay tau=10 ms', ...
    'J Neurosci 2015 DOI 10.1523/JNEUROSCI.3977-14.2015';
    'Jahnke2015','Jahnke et al. 2015','I','I','Alpha-kernel inhibitory', ...
    'alpha(t)=exp(-t/tau2)-exp(-t/tau1), I_syn via conductance state g_syn', ...
    0.3, 2.0, 'Kernel taus from manuscript; separate g_syn decay tau=10 ms', ...
    'J Neurosci 2015 DOI 10.1523/JNEUROSCI.3977-14.2015';

    % Taxidis 2012
    'Taxidis2012','Taxidis et al. 2012','CA3 PYR','CA3 PYR','Fast AMPA', ...
    'Fast chemical synapse (conductance-based), physiological PSP templates', ...
    NaN, NaN, 'Detailed constants in paper/model tables; CA3 recurrent excitation', ...
    'Hippocampus 2012 DOI 10.1002/hipo.20930';
    'Taxidis2012','Taxidis et al. 2012','CA3 PYR','CA3 INT','Fast AMPA', ...
    'Fast chemical synapse (conductance-based), physiological PSP templates', ...
    NaN, NaN, 'Feedforward/recurrent excitation onto inhibitory cells', ...
    'Hippocampus 2012 DOI 10.1002/hipo.20930';
    'Taxidis2012','Taxidis et al. 2012','CA3 INT','CA3 PYR','Fast GABA_A', ...
    'Fast chemical synapse (conductance-based), physiological PSP templates', ...
    NaN, NaN, 'Fast recurrent inhibition', ...
    'Hippocampus 2012 DOI 10.1002/hipo.20930';
    'Taxidis2012','Taxidis et al. 2012','CA3 PYR','CA1 PYR','Schaffer AMPA', ...
    'Fast chemical Schaffer collateral synapse onto CA1', ...
    NaN, NaN, 'Feedforward CA3 to CA1 drive', ...
    'Hippocampus 2012 DOI 10.1002/hipo.20930';
    'Taxidis2012','Taxidis et al. 2012','CA3 PYR','CA1 INT','Schaffer AMPA', ...
    'Fast chemical Schaffer collateral synapse onto CA1 interneurons', ...
    NaN, NaN, 'Feedforward recruitment of CA1 inhibition', ...
    'Hippocampus 2012 DOI 10.1002/hipo.20930';
    'Taxidis2012','Taxidis et al. 2012','CA1 PYR','CA1 INT','Fast AMPA', ...
    'Fast recurrent excitatory feedback onto interneurons', ...
    NaN, NaN, 'Supports ripple timing via E-I loop', ...
    'Hippocampus 2012 DOI 10.1002/hipo.20930';
    'Taxidis2012','Taxidis et al. 2012','CA1 INT','CA1 PYR','Fast GABA_A', ...
    'Fast recurrent inhibition in CA1', ...
    NaN, NaN, 'Core ripple pacing pathway in model', ...
    'Hippocampus 2012 DOI 10.1002/hipo.20930';

    % Ramirez-Villegas 2018
    'RamirezVillegas2018','Ramirez-Villegas et al. 2018','CA3 PYR','CA1 PYR dendrite','Schaffer AMPA/NMDA', ...
    'Compartmental conductance synapse onto CA1 SR dendritic compartment', ...
    NaN, NaN, 'Slow-gamma coordination and SW envelope contributions reported', ...
    'Neuron 2018 DOI 10.1016/j.neuron.2018.09.041';
    'RamirezVillegas2018','Ramirez-Villegas et al. 2018','CA3 PYR','CA1 INT','Feedforward AMPA', ...
    'Compartmental conductance synapse', ...
    NaN, NaN, 'CA3 drive recruits CA1 inhibition', ...
    'Neuron 2018 DOI 10.1016/j.neuron.2018.09.041';
    'RamirezVillegas2018','Ramirez-Villegas et al. 2018','CA1 PYR','CA1 INT soma','Recurrent AMPA', ...
    'Compartmental conductance synapse (critical for sparsity/timing)', ...
    NaN, NaN, 'Main text highlights this pathway as key for replay sparsity', ...
    'Neuron 2018 DOI 10.1016/j.neuron.2018.09.041';
    'RamirezVillegas2018','Ramirez-Villegas et al. 2018','CA1 INT','CA1 PYR soma','Fast GABA_A', ...
    'Compartmental conductance inhibition pacing ripple spiking', ...
    NaN, NaN, 'Feedback inhibition controls ripple-related sequence content', ...
    'Neuron 2018 DOI 10.1016/j.neuron.2018.09.041';

    % Canakci 2017
    'Canakci2017','Canakci et al. 2017','External Poisson','PC','AMPA Exp2Syn', ...
    'g(t)=w*(exp(-t/tau_d)-exp(-t/tau_r)); I=g*(V-E)', ...
    0.5, 3.5, 'Paper reports excitatory rise/decay constants', ...
    'PLoS ONE 2017 DOI 10.1371/journal.pone.0184542';
    'Canakci2017','Canakci et al. 2017','External Poisson','BC','AMPA Exp2Syn', ...
    'g(t)=w*(exp(-t/tau_d)-exp(-t/tau_r)); I=g*(V-E)', ...
    0.5, 3.5, 'Paper reports excitatory rise/decay constants', ...
    'PLoS ONE 2017 DOI 10.1371/journal.pone.0184542';
    'Canakci2017','Canakci et al. 2017','PC','BC','AMPA Exp2Syn', ...
    'g(t)=w*(exp(-t/tau_d)-exp(-t/tau_r)); I=g*(V-E)', ...
    0.5, 3.5, 'Recurrent excitation from active pyramidal cells', ...
    'PLoS ONE 2017 DOI 10.1371/journal.pone.0184542';
    'Canakci2017','Canakci et al. 2017','BC','PC','GABA_A Exp2Syn', ...
    'g(t)=w*(exp(-t/tau_d)-exp(-t/tau_r)); I=g*(V-E)', ...
    0.4, 5.0, 'Fast inhibition from basket cells', ...
    'PLoS ONE 2017 DOI 10.1371/journal.pone.0184542';
    'Canakci2017','Canakci et al. 2017','BC','BC','Gap junction', ...
    'I_gap = g_gap*(V_pre - V_post)', ...
    NaN, NaN, 'Electrical coupling among neighboring basket cells', ...
    'PLoS ONE 2017 DOI 10.1371/journal.pone.0184542';

    % BlueBrain CA1 / this repository
    'BlueBrainCA1','Blue Brain CA1 (this repo)','PC','PVBC','ProbAMPANMDA_EMS', ...
    'g=g_AMPA+g_NMDA with dual-exp states; STP (Use,Dep,Fac); NMDA mg gate mggate=1/(1+exp(0.062*(-V))*mg/2.62)', ...
    0.2, 1.7, 'AMPA tau_r/tau_d defaults from mod; also NMDA tau_r=9 ms, tau_d=61 ms', ...
    'modfiles/ProbAMPANMDA_EMS.mod';
    'BlueBrainCA1','Blue Brain CA1 (this repo)','PC','PVBC','DetAMPANMDA', ...
    'Dual-exp AMPA/NMDA with deterministic Tsodyks-Markram style state variables (R,u,Pr)', ...
    0.2, 1.7, 'Deterministic counterpart; NMDA tau_r=9 ms, tau_d=61 ms', ...
    'modfiles/DetAMPANMDA.mod';
    'BlueBrainCA1','Blue Brain CA1 (this repo)','PVBC','PC','ProbGABAAB_EMS', ...
    'g=g_GABAA+g_GABAB with dual-exp states; STP (Use,Dep,Fac)', ...
    0.2, 8.0, 'GABAB taus: tau_r=3.5 ms, tau_d=260.9 ms', ...
    'modfiles/ProbGABAAB_EMS.mod';
    'BlueBrainCA1','Blue Brain CA1 (this repo)','PVBC','PC','DetGABAAB', ...
    'Dual-exp GABAA/GABAB deterministic STP variant', ...
    0.2, 8.0, 'GABAB taus: tau_r=3.5 ms, tau_d=260.9 ms', ...
    'modfiles/DetGABAAB.mod';
    'BlueBrainCA1','Blue Brain CA1 (this repo)','PVBC','PVBC','Gap junction', ...
    'I_gap = (V_post - V_gap)*(g*1e-3)', ...
    NaN, NaN, 'Electrical coupling via point-process gap mechanism', ...
    'modfiles/gap.mod';

    % Bezaire full-scale CA1 (exact synapse mechanisms from mbezaire/ca1)
    'Bezaire2017','Bezaire et al. full-scale CA1 (mbezaire/ca1)','PC','PVBC','MyExp2Sid', ...
    'Dual-exponential conductance g=B-A with NET_RECEIVE weight pulse; I=g*(V-E)', ...
    0.1, 10.0, 'Default placeholders in mod; actual tau1/tau2 set per connection dataset at runtime', ...
    'mbezaire/ca1: MyExp2Sid.mod';
    'Bezaire2017','Bezaire et al. full-scale CA1 (mbezaire/ca1)','PC','PVBC','MyExp2Sidnw', ...
    'MyExp2Sid with additional multiplicative weight scale nw (distance/target dependent)', ...
    0.1, 10.0, 'Default placeholders in mod; actual tau1/tau2 and nw come from connectivity setup', ...
    'mbezaire/ca1: MyExp2Sidnw.mod';
    'Bezaire2017','Bezaire et al. full-scale CA1 (mbezaire/ca1)','PVBC','PC','ExpGABAab', ...
    'Dual-component inhibitory synapse: i=ga*(V-ea)+gb*(V-eb), each as exp2 state pair', ...
    0.1, 10.0, 'Defaults in mod; effective GABAA/GABAB taus are assigned from cellType SynList parameters', ...
    'mbezaire/ca1: ExpGABAab.mod';
    'Bezaire2017','Bezaire et al. full-scale CA1 (mbezaire/ca1)','PVBC','PVBC','ExpGABAab', ...
    'Dual-component inhibitory synapse: i=ga*(V-ea)+gb*(V-eb), each as exp2 state pair', ...
    0.1, 10.0, 'Defaults in mod; effective GABAA/GABAB taus are assigned from cellType SynList parameters', ...
    'mbezaire/ca1: ExpGABAab.mod';
    'Bezaire2017','Bezaire et al. full-scale CA1 (mbezaire/ca1)','PVBC','PVBC','Electrical coupling / fastconn', ...
    'Gap-like/electrical pathway handled by dedicated connectivity/event mechanisms (fastconn/repeatconn)', ...
    NaN, NaN, 'Electrical and event-routing mechanisms are separate from Exp2 synapse point processes', ...
    'mbezaire/ca1: fastconn.mod, repeatconn.mod'
};

synapse_tbl = cell2table(synapse_rows, 'VariableNames', ...
    {'paper_id','citation','source_population','target_population','synapse_family', ...
     'equation_template','tau_rise_ms','tau_decay_ms','notes','source'});

end
